name: Riverside Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33882
title: RIVERSIDE FILMS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#902223'
    - '#c9c9c9'
    - '#797979'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
